<a href="https://colab.research.google.com/github/josephhalejr/Sales/blob/main/Copy_of_Copy_of_Copy_of_Distance_and_time_josephhale.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Starter Code

# Exploring NumPy Arrays: Distance and Time

1) Import the numpy library

In [ ]:
import numpy as np

2) Create a numpy array called "distance" that includes the following distances (in meters): 100, 200, 400, 800, 1500, 3000, 5000, 10000

In [ ]:
distance_array = ([100, 200,400, 800, 1500, 3000, 5000, 10000])

3) Use the min() and max() functions to find the minimum and maximum distances

In [ ]:
min(distance_array)

100

In [ ]:
max(distance_array)

10000

4) To find the average distance, use the np.mean() function

In [ ]:
from numpy.lib.function_base import average
average = sum(distance_array)/len(distance_array)
print(average)

2625.0


5) use the sum() function to find the total distance

In [ ]:
sum(distance_array)

21000

6) Another valuable function is the cumsum() function which outputs the cumulative sum...notice the output will be 100, 300, 700 as it adds each new distance

In [ ]:
distance_array = np.array([100, 200, 400, 800, 1500, 3000, 5000,10000])
distance_array.cumsum()

array([  100,   300,   700,  1500,  3000,  6000, 11000, 21000])

7) To round all of the values in an array, use np.round()

In [ ]:
np.round(distance_array, decimals = 0, out = None)

array([  100,   200,   400,   800,  1500,  3000,  5000, 10000])

8) Create a numpy array called time that includes the following times (in seconds):  10.62, 21.34, 48.25, 113.43, 233.96, 506.53, 866.17, 1757.45

In [ ]:
time = np.array([10.62, 21.34, 48.25, 113.43,223.96, 506.53, 866.17, 1757.45])
print(time)

[  10.62   21.34   48.25  113.43  223.96  506.53  866.17 1757.45]


9) the values in your time array correspond to olympic records for running the corresponding distances.  Perform the calculation needed to find the speed (in m/s) for each record distance

In [ ]:
speed = distance_array/time
print(speed)

[9.41619586 9.37207123 8.29015544 7.0528079  6.69762458 5.92265019
 5.77253888 5.69006231]


10) One common problem data scientists run into is that we are given information in units that are not consistent.  
For example, we might want to compare data that is given in meters to second to data that is given in miles per hour. A cheetah is the fastest land animal which can reach speeds of 75.0 miles per hour.  
In order to compare our olympians to a cheetah, we need to be able to convert from one unit to another.
Perform calculations to convert the olympic record speeds from meters/second into miles per hour.  Note: 1 meter = 0.00062 miles
How do our olympians compare to the cheetah?

In [ ]:
speed2 = ([9.41619586 9.37207123 8.29015544 7.0528079  6.69762458 5.92265019
 5.77253888 5.69006231]) * 0.00062
print(speed2)

SyntaxError: ignored