<a href="https://colab.research.google.com/github/josephhalejr/Sales/blob/main/Copy_of_josephhalenumpyexercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
price = [2, 1, 10]
type(price)

list

In [ ]:
quantity_sold = [17, 40, 1]
type(quantity_sold)

list

In [ ]:
import numpy as np


In [ ]:
price_array = np.array(price)
quantity_sold_array = np.array(quantity_sold)
type(price_array)

numpy.ndarray

In [ ]:
price_array * quantity_sold_array

array([34, 40, 10])

In [ ]:
cost_array = np.array ([0.25, 0.5, 5.00])



In [ ]:
profit_array = price_array - cost_array
print(profit_array)

[1.75 0.5  5.  ]


In [ ]:
profit_array > 2.00

array([False, False,  True])

In [ ]:
price_array = price_array + [7]
print(price_array)

[ 9  8 17]


In [ ]:
# just fixing the mistake
price_array = price_array - [7]
# the proper way to append an element to an array
price_array = np.append(price_array, 7)
print(price_array)
                        

[ 2  1 10  7]


In [ ]:
price_array = np.append(price_array, [4.5, 3, 4, 9])
print(price_array)                       

[ 2.   1.  10.   7.   4.5  3.   4.   9. ]


In [ ]:
print(price_array.dtype)

float64


In [ ]:
price_array = np.delete(price_array, -1)
print(price_array)

[ 2.   1.  10.   7.   4.5  3.   4. ]


In [ ]:
price_array[2] = 12
print(price_array)

[ 2.   1.  12.   7.   4.5  3.   4. ]


In [ ]:
quantity_sold_array = np.append(quantity_sold_array,[2, 3, 16, 5])
print(quantity_sold_array)
quantity_sold_array[1] = 39

[17 40  1  2  3 16  5]


In [ ]:
price_array * quantity_sold_array

array([34. , 39. , 12. , 14. , 13.5, 48. , 20. ])

In [ ]:

print(quantity_sold_array)

[17 39  1  2  3 16  5]


In [ ]:
quantity_leftover = np.array([ 0, 0, 2, 1, 6, 0, 2])


In [ ]:
quantity_leftover * (price_array/2)


array([ 0. ,  0. , 12. ,  3.5, 13.5,  0. ,  4. ])

In [ ]:
sum(quantity_leftover * (price_array/2))

33.0